SELECT IT.ITEM_ID, IT.ITEM_NAME, IT.RARITY
FROM ITEM_INFO IT
JOIN ITEM_TREE T ON IT.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY IT.ITEM_ID DESC;