# SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, r.CREATED_DATE
# FROM USED_GOODS_BOARD b JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
# WHERE b.CREATED_DATE >= DATE '2022-10-01' AND b.CREATED_DATE < DATE '2022-11-01'
# ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;

# SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
# WHERE B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'AND R.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
# ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;


SELECT UGB.TITLE, UGB.BOARD_ID, UBR.REPLY_ID, UBR.WRITER_ID, UBR.CONTENTS, 	DATE_FORMAT(UBR.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD UGB, USED_GOODS_REPLY UBR
WHERE UGB.BOARD_ID = UBR.BOARD_ID AND UGB.CREATED_DATE LIKE '2022-10%' 
ORDER BY UBR.CREATED_DATE, UGB.TITLE 